# Generated by Django 3.2.4 on 2021-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True),
        ),
    ]
