# Generated by Django 3.2.4 on 2021-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
